version: '3.1'

services:

  game_store_api:
    container_name: game_store_api_container
    build:
      context: .
    image: game_store_api_image
    restart: always
    ports:
      - 8081:8080
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://game_store_mariadb:3306/game_store
      - SPRING_DATASOURCE_USERNAME=dev
      - SPRING_DATASOURCE_PASSWORD=dev
    depends_on:
      - game_store_mariadb

  game_store_mariadb:
    container_name: game_store_mariadb_container
    image: library/mariadb:10.5
    restart: always
    ports:
      - 3306:3306
    volumes:
      - ./db:/var/lib/mysql:rw
    environment:
      - MYSQL_DATABASE=game_store
      - MYSQL_USER=dev
      - MYSQL_PASSWORD=dev
      - MYSQL_RANDOM_ROOT_PASSWORD=yes